# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NpmiGo < Formula
  desc "npmi-go caches the contents of node_modules directory in a tarball stored locally or in a Minio instance"
  homepage "https://github.com/hermo/npmi-go"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hermo/npmi-go/releases/download/v0.8.0/npmi-go_0.8.0_macOS_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1b869428f573f34315982b0215324348320e54210dd60c696e989c8779b04a05"

      def install
        bin.install "npmi-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hermo/npmi-go/releases/download/v0.8.0/npmi-go_0.8.0_macOS_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "babf84cbc26819c24d0217b392d2c92f4a4804480bf8d4e95f9c813956c53c4b"

      def install
        bin.install "npmi-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hermo/npmi-go/releases/download/v0.8.0/npmi-go_0.8.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9d971261c74dce1e0d4216ac4b7912d6e8e972e590244b10f0c8cd644b93a2d1"

      def install
        bin.install "npmi-go"
      end
    end
  end

  def caveats; <<~EOS
    Note that npmi-go is work-in-progress and should not be used in production.
  EOS
  end
end
